### ISSUE TITLE
Error: Problems were encountered

### ISSUE THREAD

**Issue by perlun** [neenhouse/npm-flatten#1]
Hi,

Just tried the `npm-flatten` package, but ran into this error:

```
shrinkwrapping...
stdout:
stderr: npm WARN unmet dependency /Users/plundberg/git/uxf/ecraft.uxfactory.html/node_modules/glob-stream requires event-stream@'~3.0.20' but will load
npm WARN unmet dependency /Users/plundberg/git/uxf/ecraft.uxfactory.html/node_modules/event-stream,
npm WARN unmet dependency which is version 3.1.1
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: glob-watcher@0.0.6 /Users/plundberg/git/uxf/ecraft.uxfactory.html/node_modules/glob-watcher
npm ERR! extraneous: glob2base@0.0.8 /Users/plundberg/git/uxf/ecraft.uxfactory.html/node_modules/glob2base
npm ERR! extraneous: graceful-fs@2.0.3 /Users/plundberg/git/uxf/ecraft.uxfactory.html/node_modules/graceful-fs
npm ERR! extraneous: lru-cache@2.5.0 /Users/plundberg/git/uxf/ecraft.uxfactory.html/node_modules/lru-cache
npm ERR! extraneous: ordered-read-streams@0.0.7 /Users/plundberg/git/uxf/ecraft.uxfactory.html/node_modules/ordered-read-streams
npm ERR! extraneous: sigmund@1.0.0 /Users/plundberg/git/uxf/ecraft.uxfactory.html/node_modules/sigmund
npm ERR! extraneous: unique-stream@0.0.5 /Users/plundberg/git/uxf/ecraft.uxfactory.html/node_modules/unique-stream
npm ERR! invalid: event-stream@3.1.1 /Users/plundberg/git/uxf/ecraft.uxfactory.html/node_modules/event-stream
npm ERR! extraneous: globule@0.1.0 /Users/plundberg/git/uxf/ecraft.uxfactory.html/node_modules/globule
npm ERR! extraneous: gulp-batch@0.4.1 /Users/plundberg/git/uxf/ecraft.uxfactory.html/node_modules/gulp-batch
npm ERR!     at shrinkwrap_ (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:29:15)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:23:5
npm ERR!     at /usr/local/lib/node_modules/npm/lib/ls.js:43:30
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:119:5
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! cwd /Users/plundberg/git/uxf/ecraft.uxfactory.html
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/plundberg/git/uxf/ecraft.uxfactory.html/npm-debug.log
npm ERR! not ok code 0
```

Any ideas about how to solve it?

**Comment by beuted** [comment]
Same error here, here is the full logs :

I'm on windows
```
$ npm -v
1.4.28
```

```
$ node -v
v0.10.33
```

package.json :

```
{
  "name": "npm-flatten-error-test",
  "author": "CRITEO FastTrack Team",
  "private": true,
  "version": "0.0.0",
  "licenses": {},
  "devDependencies": {},
  "dependencies": {
    "grunt": "^0.4.5"
  }
}
```

```
$ npm-flatten
shrinkwrapping...
stdout: wrote npm-shrinkwrap.json

stderr:
reading npm-shrinkwrap.json...
Found async@0.1.22...
Found coffee-script@1.3.3...
Found colors@0.6.2...
Found dateformat@1.0.2-1.2.3...
Found eventemitter2@0.4.14...
Found findup-sync@0.1.3...
Found glob@3.2.11...
Found inherits@2.0.1...
Found minimatch@0.3.0...
Found lru-cache@2.5.0...
Found sigmund@1.0.0...
Found lodash@2.4.1...
Found glob@3.1.21...
Found graceful-fs@1.2.3...
Found inherits@1.0.0...
Found hooker@0.2.3...
Found iconv-lite@0.2.11...
Found minimatch@0.2.14...
Found lru-cache@2.5.0...
Found sigmund@1.0.0...
Found nopt@1.0.10...
Found abbrev@1.0.5...
Found rimraf@2.2.8...
Found lodash@0.9.2...
Found underscore.string@2.2.1...
Found which@1.0.9...
Found js-yaml@2.0.5...
Found argparse@0.1.16...
Found underscore@1.7.0...
Found underscore.string@2.4.0...
Found esprima@1.0.4...
Found exit@0.1.2...
Found getobject@0.1.0...
Found grunt-legacy-util@0.2.0...
Found grunt-legacy-log@0.1.1...
Found lodash@2.4.1...
Found underscore.string@2.3.3...
37 deps need to be flattened...
stdout: inherits@2.0.1 node_modules\inherits

abbrev@1.0.5 node_modules\abbrev

dateformat@1.0.2-1.2.3 node_modules\dateformat

which@1.0.9 node_modules\which

sigmund@1.0.0 node_modules\sigmund

eventemitter2@0.4.14 node_modules\eventemitter2

getobject@0.1.0 node_modules\getobject

graceful-fs@1.2.3 node_modules\graceful-fs

rimraf@2.2.8 node_modules\rimraf

colors@0.6.2 node_modules\colors

lru-cache@2.5.0 node_modules\lru-cache

nopt@1.0.10 node_modules\nopt

underscore@1.7.0 node_modules\underscore

async@0.1.22 node_modules\async

hooker@0.2.3 node_modules\hooker

minimatch@0.3.0 node_modules\minimatch

exit@0.1.2 node_modules\exit

argparse@0.1.16 node_modules\argparse

js-yaml@2.0.5 node_modules\js-yaml

glob@3.2.11 node_modules\glob
├── inherits@2.0.1
└── minimatch@0.3.0

underscore.string@2.2.1 node_modules\underscore.string

coffee-script@1.3.3 node_modules\coffee-script

iconv-lite@0.2.11 node_modules\iconv-lite

esprima@1.0.4 node_modules\esprima

lodash@2.4.1 node_modules\lodash

grunt-legacy-util@0.2.0 node_modules\grunt-legacy-util
└── underscore.string@2.2.1

findup-sync@0.1.3 node_modules\findup-sync
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
└── lodash@2.4.1

grunt-legacy-log@0.1.1 node_modules\grunt-legacy-log
├── underscore.string@2.3.3
└── lodash@2.4.1

stderr: npm WARN unmet dependency c:\hey\node_modules\argparse requires underscore.string@'~2.4.0' but will load
npm WARN unmet dependency c:\hey\node_modules\underscore.string,
npm WARN unmet dependency which is version 2.2.1
npm WARN unmet dependency c:\hey\node_modules\grunt-legacy-util requires lodash@'~0.9.2' but will load
npm WARN unmet dependency c:\hey\node_modules\lodash,
npm WARN unmet dependency which is version 2.4.1

npm dedupe....
stdout:
stderr: npm WARN unavoidable conflict glob { 'c:\\hey\\node_modules\\glob': '3.2.11',
npm WARN unavoidable conflict   'c:\\hey\\node_modules\\grunt\\node_modules\\glob': '3.1.21' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict lodash { 'c:\\hey\\node_modules\\grunt\\node_modules\\lodash': '0.9.2',
npm WARN unavoidable conflict   'c:\\hey\\node_modules\\lodash': '2.4.1' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict minimatch { 'c:\\hey\\node_modules\\grunt\\node_modules\\minimatch': '0.2.14',
npm WARN unavoidable conflict   'c:\\hey\\node_modules\\minimatch': '0.3.0' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict underscore.string { 'c:\\hey\\node_modules\\grunt\\node_modules\\underscore.string': '2.2.1',
npm WARN unavoidable conflict   'c:\\hey\\node_modules\\underscore.string': '2.2.1' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict inherits { 'c:\\hey\\node_modules\\findup-sync\\node_modules\\glob\\node_modules\\inherits': '2.0.1',
npm WARN unavoidable conflict   'c:\\hey\\node_modules\\glob\\node_modules\\inherits': '2.0.1',
npm WARN unavoidable conflict   'c:\\hey\\node_modules\\grunt\\node_modules\\glob\\node_modules\\inherits': '1.0.0',
npm WARN unavoidable conflict   'c:\\hey\\node_modules\\inherits': '2.0.1' }
npm WARN unavoidable conflict Not de-duplicating

shrinkwrapping again...
stdout:
stderr: npm WARN unmet dependency c:\hey\node_modules\argparse requires underscore.string@'~2.4.0' but will load
npm WARN unmet dependency c:\hey\node_modules\underscore.string,
npm WARN unmet dependency which is version 2.2.1
npm WARN unmet dependency c:\hey\node_modules\grunt-legacy-util requires lodash@'~0.9.2' but will load
npm WARN unmet dependency c:\hey\node_modules\lodash,
npm WARN unmet dependency which is version 2.4.1
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: lodash@2.4.1 c:\hey\node_modules\lodash
npm ERR! invalid: underscore.string@2.2.1 c:\hey\node_modules\underscore.string
npm ERR!     at shrinkwrap_ (c:\Program Files (x86)\nodejs\node_modules\npm\lib\shrinkwrap.js:30:15)
npm ERR!     at c:\Program Files (x86)\nodejs\node_modules\npm\lib\shrinkwrap.js:24:5
npm ERR!     at c:\Program Files (x86)\nodejs\node_modules\npm\lib\ls.js:45:30
npm ERR!     at c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:130:5
npm ERR!     at c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:244:14
npm ERR!     at cb (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
npm ERR!     at c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:244:14
npm ERR!     at cb (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
npm ERR!     at c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:244:14
npm ERR!     at cb (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files (x86)\\nodejs\\\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "shrinkwrap"
npm ERR! cwd c:\hey
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by bhalajin** [comment]
I know this is an old post. But I did encounter the same problem.

npm ERR! invalid happens when the dependency tree encounters more than one version of the package and it would raise this error.

As a solution, npm update on the package should be done and then if npm-flatten is done again, the flattening would happen properly.

**Comment by perlun** [comment]
Dead old, closing.
